format = """
$os\
$username\
$hostname\
$rust$python$node$lua\
$git_branch$git_status$git_state\
$cmd_duration\
$fill\
$time\
$line_break\
$directory$sudo$character
"""
add_newline = false
palette = "gruvbox"

[fill]
symbol = " "

[time]
disabled = false
format = '[ ó°… $time ]($style)'
time_format = "%T"
style ="bold fg:magenta bg:dark-gray"

[cmd_duration]
min_time = 500
format = '[ took $duration ](bold fg:bg bg:dark-green)'


[character]
success_symbol = "[ó°˜§](bold green)"
error_symbol = "[î«²](bold red)"

[sudo]
style = "bold red"
symbol = "î©¬ "
format = "[$symbol]($style)"
disabled = false

[username]
style_user = "fg:bg bg:dark-blue bold"
style_root = "green bold"
format = "[ $user ]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[ $ssh_symbol](bold fg:blue bg:blue)[$hostname ](bold fg:bg bg:blue)"
trim_at = ".companyname.com"
disabled = false

[os]
disabled = false
style = "bg:dark-gray"

[os.symbols]
Arch =  "[ ïŒƒ  ](fg:blue $style)"
NixOS = "[ ïŒ“  ](fg:blue $style)"
Macos = "[ îœ‘  ](fg:red $style)"
Linux = "[ î¯†  ](fg:fg $style)"
Unknown = "[ ïŒ®  ](fg:green $style)"

[palettes.gruvbox]
fg = "#ebdbb2"
bg = "#1d2021"
yellow = "#fabd2f"
dark-yellow = "#d79921"
green = "#b8bb26"
dark-green = "#98971a"
red = "#fb4932"
dark-red = "#cc241d"
magenta = "#d3869b"
dark-magenta = "#b16286"
blue = "#83a598"
dark-blue = "#458588"
cyan = "#8ec07c"
dark-cyan = "#689d6a"
gray = "#666666"
dark-gray = "#3d3d3d"

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = true

[memory_usage]
disabled = false
threshold = -1
symbol = " ó°› "
format = "[$symbol]($style)[$ram( | $swap) ]($style)"
style = "bold fg:dark-green"

[line_break]
disabled = false

[c]
symbol = "î˜ "
detect_extensions = ["c", "h", "cpp"]

[directory]
read_only = " ï€£"
home_symbol = " ~"
truncation_length = 4
truncation_symbol = 'â€¦/'
truncate_to_repo = true


[docker_context]
symbol = "ïŒˆ "

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ](bg:dark-magenta fg:bg bold)"
symbol = "ï˜ "

[git_status]
format='([\[$all_status$ahead_behind\]](bg:dark-magenta fg:bg bold))'
#up_to_date = 'âœ“'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '+($count)'

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[lua]
symbol = "î˜  "
format = '[$symbol$version](red bold) '

[meson]
symbol = "â¬¢ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ğŸ“¦ "

[python]
symbol = "îˆµ "
format = '[ $symbol$version ](bg:dark-yellow fg:bg bold)'

[rust]
symbol = "ğŸ¦€ "
format = '[ $symbol$version ](bg:dark-yellow fg:bg bold)'
