format = """
$os\
$username\
[\ue0bc](fg:dark-blue bg:red)\
$hostname\
[\ue0bc](fg:red bg:dark-yellow)\
$rust$python$node$lua\
[\ue0bc](fg:dark-yellow bg:dark-magenta)\
$git_branch$git_status$git_state\
[\ue0bc](fg:dark-magenta)\
$cmd_duration\
$fill\
[\ue0be](fg:dark-green)\
$memory_usage\
[\ue0be](fg:dark-yellow bg:dark-green)\
$time\
$line_break\
$directory$sudo$character
"""
add_newline = false
palette = "gruvbox"

[fill]
symbol = " "

[time]
disabled = false
format = '[ $time ]($style)'
time_format = "%T"
style ="fg:bg bold bg:dark-yellow"

[cmd_duration]
min_time = 500
format = ' took [$duration](bold yellow)'


[character]
success_symbol = "[ï¬¦](bold green)"
error_symbol = "[ï¬¦](bold red)"

[sudo]
style = "bold red"
symbol = "î©¬ "
format = "[$symbol]($style)"
disabled = false

[username]
style_user = "fg:bg bg:dark-blue bold"
style_root = "green bold"
format = "[ $user ]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[ $ssh_symbol](bold fg:blue bg:red)[$hostname ](bold bg:red fg:bg)"
trim_at = ".companyname.com"
disabled = false

[os]
disabled = false
style = "bg:dark-blue"

[os.symbols]
Arch =  "[ ïŒƒ ](fg:bg $style)"
NixOS = "[ ïŒ“ ](fg:blue $style)"
Macos = "[ îœ‘ ](fg:red $style)"
Linux = "[ î¯† ](fg:fg $style)"

[palettes.gruvbox]
fg = "#ebdbb2"
bg = "#1d2021"
yellow = "#fabd2f"
dark-yellow = "#d79921"
green = "#b8bb26"
dark-green = "#98971a"
red = "#fb4932"
dark-red = "#cc241d"
magenta = "#d3869b"
dark-magenta = "#b16286"
blue = "#83a598"
dark-blue = "#458588"
cyan = "#8ec07c"
dark-cyan = "#689d6a"
gray = "#666666"
dark-gray = "#3d3d3d"

[localip]
ssh_only = false
format = "@[$localipv4](bold red) "
disabled = true

[memory_usage]
disabled = false
threshold = -1
symbol = " ï¡š "
format = "[$symbol]($style)[$ram( | $swap) ]($style)"
style = "bold fg:bg bg:dark-green"

[line_break]
disabled = false

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "
detect_extensions = ["c", "h", "cpp"]

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[directory]
read_only = " ï ½"
home_symbol = " ~"
truncation_length = 4
truncation_symbol = 'â€¦/'
truncate_to_repo = true


[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ](bg:dark-magenta fg:bg bold)"
symbol = "ï˜ "

[git_status]
format='([\[$all_status$ahead_behind\]](bg:dark-magenta fg:bg bold))'
#up_to_date = 'âœ“'
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '+($count)'

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "
format = '[$symbol$version](red bold) '

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "
format = '[ $symbol$version ](bg:dark-yellow fg:bg bold)'

[rlang]
symbol = "ï³’ "

[ruby]
symbol = "î‘ "

[rust]
symbol = "ğŸ¦€ "
format = '[ $symbol$version ](bg:dark-yellow fg:bg bold)'

[scala]
symbol = "îœ· "

[spack]
symbol = "ğŸ…¢ "
